#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate OPEN.md and docs/open-items-snapshot.md from the tracker source.

    python3 tests/tracker-export.py

The tracker is docs/tracker/open-items.html. Its item data lives in a single
<script id="appdata" type="application/json"> block, so it can be read and written by
anything -- this script, Copilot, a human with an editor -- without parsing HTML.

WHY THIS EXISTS. The tracker used to be a hosted page only, and the way to get its
contents into the repository was to press Export, press Download, find the file, and copy
it over OPEN.md. Four manual steps is three too many, and OPEN.md drifted. Now the tracker
has a file, and "sync" is one command.

WHAT IT DOES NOT DO. It cannot read the published page at claude.ai. If notes were typed
there and published, that version is ahead of this file and has to come back first --
either by exporting from the page, or by asking a session with artifact access to read it.
The published page and this file are the same source; they are not the same copy.

Both outputs are written identically, because tests/check-index.sh fails the build when
OPEN.md and its in-repo snapshot disagree.
"""
import json
import os
import re
import subprocess
import sys

MARK = {"open": "[ ]", "doing": "[~]", "done": "[x]", "dropped": "[-]"}
ARTIFACT = "https://claude.ai/code/artifact/bbac4a10-81b5-49bb-b206-46e4cbe6d303"


def repo_root():
    try:
        out = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except Exception:
        return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(path):
    src = open(path, encoding="utf-8").read()
    m = re.search(r'<script id="appdata" type="application/json">(.*?)</script>', src, re.S)
    if not m:
        sys.exit("no appdata block in %s -- the tracker source is not what this expects" % path)
    try:
        return json.loads(m.group(1))
    except json.JSONDecodeError as e:
        sys.exit("appdata is not valid JSON (%s). The tracker will render blank in a browser "
                 "too, so fix it there and the page comes back." % e)


def render(state):
    L = ["# Open items", ""]
    L.append("*Generated by `tests/tracker-export.py` from `docs/tracker/open-items.html`.*")
    L.append("*Do not edit this file by hand: edit the tracker and run the exporter again.*")
    L.append("")
    L.append("Applicant: **Ranaji Deb**, sole applicant, in his own name.")
    L.append("")
    L.append("> **The tracker.** Source: `project/docs/tracker/open-items.html` — open it by")
    L.append("> double-clicking it, or let Copilot edit it in place.")
    L.append("> Published copy: <%s>" % ARTIFACT)
    L.append("> Same source, two copies. Whichever was edited last is the one to export from.")
    L.append("> To regenerate this file: `python3 tests/tracker-export.py`")
    L.append("")

    st = state.get("stamp") or {}
    if st:
        L.append("> **Currency.** Swept %s, repo at %s. %s"
                 % (st.get("swept", "?"), st.get("commit", "?"), st.get("covers", "")))
        for e in st.get("log", []):
            L.append(">   - %s — %s" % (e["d"], e["t"]))
        L.append("")

    L.append("Status marks: `[ ]` open · `[~]` in progress · `[x]` done · `[-]` dropped or "
             "deferred on purpose.")
    L.append("")

    for idx, s in enumerate(state["sections"]):
        L.append("## %d. %s" % (idx + 1, s["title"]))
        L.append("")
        if s.get("note"):
            L.append(s["note"])
            L.append("")
        for i in s["items"]:
            line = "- %s **%s**" % (MARK.get(i["status"], "[ ]"), i["t"])
            if i.get("due"):
                line += " _(by %s)_" % i["due"]
            L.append(line)
            if i.get("d"):
                L.append("      " + i["d"])
            if i.get("blocks"):
                L.append("      *Blocks: %s*" % i["blocks"])
            if i.get("touched"):
                L.append("      *Moved: %s*" % i["touched"])
            if i.get("note"):
                L.append("      **Note:** " + re.sub(r"\n+", " ", i["note"]))
        L.append("")

    live = sum(1 for s in state["sections"] for i in s["items"]
               if i["status"] not in ("done", "dropped"))
    total = sum(len(s["items"]) for s in state["sections"])
    L.append("---")
    L.append("")
    L.append("%d of %d items live. Baseline swept **%s**." % (live, total, state["updated"]))
    return "\n".join(L) + "\n"


def main():
    root = repo_root()
    src = os.path.join(root, "docs", "tracker", "open-items.html")
    if not os.path.exists(src):
        sys.exit("no tracker at %s" % src)
    text = render(load(src))

    targets = [os.path.join(os.path.dirname(root), "OPEN.md"),
               os.path.join(root, "docs", "open-items-snapshot.md")]
    for t in targets:
        os.makedirs(os.path.dirname(t), exist_ok=True)
        open(t, "w", encoding="utf-8").write(text)
        print("wrote %s" % t)


if __name__ == "__main__":
    main()
